### ISSUE TITLE
Having a problem with the module and Multiple Statements in a single string.

### ISSUE THREAD

**Issue by VaasKahnGrim** [SuperiorServers/gm_tmysql4#10]
so currently I have a function which is performing a query like so:
`DB:Query("SELECT * FROM characters WHERE SteamID = '"..steam64.."'; SELECT * FROM charwhitelist WHERE SteamID = '"..steam64.."'",function(results)
    --Do Stuff with the data retrieved
end)`

However when running it like this I end up getting a syntax error. But removing the second statement stops the error from happening. Only problem is that I'm unable to perform the two queries and then run the callback function after both have been completed. as far as I can tell I'm following the doccumentation in the readme.md file but I'm ending up with this issue happening.

For context I'm converting an addon from mysqloo to tmysql4 instead.

**Comment by VaasKahnGrim** [comment]
nvm, apparently the issue was related to the DB object :/ welp thats one issue resolved. all I have to do now is figure out whats wrong with the query results and I should be good to go.

**Comment by KingofBeast** [comment]
What error specifically were you getting?

Also, were you connecting with CLIENT_MULTI_STATEMENTS ?

**Comment by VaasKahnGrim** [comment]
basically I had CLIENT_MULTI_STATEMENTS in the DB object, but I looked over the doccumentation 30 times or so and never noticed the nil value just before it in the example. so CLIENT_MULTI_STATEMENTS was basically my socketfile path lol.
