### ISSUE TITLE
Cant find tmysql.lua

### ISSUE THREAD

**Issue by rbreslin18** [SuperiorServers/gm_tmysql4#14]
I added to bin folder in server but am receiving the error that it cannot find tmysql.lua. 
Update: I fixed it by requiring tmysql4 but now I am getting this error...

```

[ERROR] gamemodes/perp/gamemode/sv_hooks.lua:4: attempt to call field 'query' (a nil value)
  1. sendOnline - gamemodes/perp/gamemode/sv_hooks.lua:4
   2. unknown - gamemodes/perp/gamemode/sv_hooks.lua:69

**Comment by X0lik** [comment]
> I added to bin folder in server but am receiving the error that it cannot find tmysql.lua. Update: I fixed it by requiring tmysql4 but now I am getting this error...
> 
> ```
> 
> [ERROR] gamemodes/perp/gamemode/sv_hooks.lua:4: attempt to call field 'query' (a nil value)
>   1. sendOnline - gamemodes/perp/gamemode/sv_hooks.lua:4
>    2. unknown - gamemodes/perp/gamemode/sv_hooks.lua:69
> ```

For others:
Cause there's no Database:query function, it names Database:Query

**Comment by aStonedPenguin** [comment]
This module is not backwards compatible with earlier versions.

https://github.com/SuperiorServers/gm_tmysql4/blob/master/README.md
