### ISSUE TITLE
Module not found!

### ISSUE THREAD

**Issue by ReapsFR** [SuperiorServers/gm_tmysql4#16]
Hello

The .dll is in my bin folder, x86, but these errors appears:

Loading tmysql module...
[ERROR] Couldn't include file 'includes\modules\tmysql.lua' - File not found or is empty (@gamemodes/perp/gamemode/sv_hooks.lua (line 35))
  1. unknown - gamemodes/perp/gamemode/sv_hooks.lua:35

[ERROR] gamemodes/perp/gamemode/sv_hooks.lua:35: Module not found!
  1. require - [C]:-1
   2. unknown - gamemodes/perp/gamemode/sv_hooks.lua:35

Help please 🙏

**Comment by aStonedPenguin** [comment]
#14
