### ISSUE TITLE
Errors number [2013] - [2014]

### ISSUE THREAD

**Issue by JarosLucky** [SuperiorServers/gm_tmysql4#9]
When I try to use the latest releases (**4.35** - **4.37**) of this module, I have a problem with queries, or rather some queries produce an error from **2013** to **2014**.

It sounds like this: "Commands out of sync; you can't run this command now".

But when I use the **4.1** version of the module, everything works fine and without errors. =\

The module is used with almost the latest version of **Dash**.

**Comment by KingofBeast** [comment]
Do you have a reproduction case I can test with?

**Comment by JarosLucky** [comment]
I will try to find a way to repeat this case.

пн, 7 сент. 2020 г., 11:43 KingofBeast <notifications@github.com>:

**Comment by KingofBeast** [comment]
I think I know what it is

Are you preparing statements while queries may possibly be running?

**Comment by KingofBeast** [comment]
I've fixed it on my end - try redownloading the binaries on the https://github.com/SuperiorServers/gm_tmysql4/releases/tag/4.37 release

**Comment by JarosLucky** [comment]
```
L 09/07/2020 - 15:48:05: "』『　        』『<2><...><>" entered the game
[MySQL] gmod:gmod@:3306 => [2013] Commands out of sync; you can't run this command now
[MySQL] gmod:gmod@:3306 => SELECT * FROM ...
```
Unfortunately, it didn't help.

**Comment by JarosLucky** [comment]
> I think I know what it is
> 
> Are you preparing statements while queries may possibly be running?

By the way, I don't use them.

**Comment by JarosLucky** [comment]
I'm now trying to figure out what the problem is, but for now I noticed that it is possible that MariaDB parses the data differently (or so) and because of this, problems arise. Although this is currently without a solid guess.

**Comment by JarosLucky** [comment]
Hell, I don't know exactly what the problem is yet. I'll try to make a simple example to reproduce, for about a week. For now, I'll be busy with other things and probably for this time I will close the request.

**Comment by KingofBeast** [comment]
I'll be happy to test and fix once you find a reproducible case
